name: Society
version: '${project.version}'
main: nl.abelkrijgtalles.society.Society
api-version: '1.20'
authors: [Abelpro678]
description: The optimal plugin for your society in Minecraft
website: https://github.com/Abelkrijgtalles/society
